// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SzakmakApi.Data;

#nullable disable

namespace SzakmakApi.Migrations
{
    [DbContext(typeof(versenyzoDbContext))]
    [Migration("20251105115702_sqlite.local_migration_776")]
    partial class sqlitelocal_migration_776
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SzakmakApi.Models.orszag", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("orszagNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("orszagok");
                });

            modelBuilder.Entity("SzakmakApi.Models.szakma", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("szakmaNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("szakmak");
                });

            modelBuilder.Entity("SzakmakApi.Models.versenyzo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("pont")
                        .HasColumnType("INTEGER");

                    b.Property<string>("szakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("orszagId");

                    b.HasIndex("szakmaId");

                    b.ToTable("versenyzok");
                });

            modelBuilder.Entity("SzakmakApi.Models.versenyzo", b =>
                {
                    b.HasOne("SzakmakApi.Models.orszag", null)
                        .WithMany("versenyzok")
                        .HasForeignKey("orszagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SzakmakApi.Models.szakma", null)
                        .WithMany("versenyzok")
                        .HasForeignKey("szakmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SzakmakApi.Models.orszag", b =>
                {
                    b.Navigation("versenyzok");
                });

            modelBuilder.Entity("SzakmakApi.Models.szakma", b =>
                {
                    b.Navigation("versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
